import { describe, it, expect } from "vitest";

import { createTestKafka } from "../../helpers/testKafka.js";
import { createEvent } from "../../../src/messaging/EventFactory.js";

describe("Kafka Consumer Receive Integration", () => {

    it("should receive published BALL_RECORDED event", async () => {

        const kafka = createTestKafka();

        const producer = kafka.producer();

        const consumer = kafka.consumer({
            groupId: `criczone-test-consumer-${Date.now()}`
        });

        const event = createEvent({
            type: "BALL_RECORDED",

            aggregateId: "test-match-1002",

            payload: {
                matchId: 1002,
                inningsId: 2002,
                playerId: 3002,
                runs: 6,

                wicket: {
                    occurred: false
                }
            },

            requestId: "test-request-002",
            traceId: "test-trace-002"
        });

        try {

            await producer.connect();
            await consumer.connect();

            await consumer.subscribe({
                topic: process.env.TEST_KAFKA_TOPIC,
                fromBeginning: false
            });

            /*
             * Register GROUP_JOIN listener before starting
             * the consumer so the event cannot be missed.
             */
            const consumerReady = new Promise((resolve) => {

                consumer.on(
                    consumer.events.GROUP_JOIN,
                    resolve
                );

            });

            /*
             * Message promise resolves directly from eachMessage.
             * No polling and no shared mutable receivedEvent variable.
             */
            let resolveMessage;
            let rejectMessage;

            const messageReceived = new Promise((resolve, reject) => {
                resolveMessage = resolve;
                rejectMessage = reject;
            });

            const timeout = setTimeout(() => {

                rejectMessage(
                    new Error(
                        "Kafka consumer did not receive event"
                    )
                );

            }, 15000);

            /*
             * Start consumer processing.
             *
             * Do not await consumer.run() here because the consumer
             * continues running until it is stopped/disconnected.
             */
            consumer.run({

                eachMessage: async ({ message }) => {

                    const parsedEvent =
                        JSON.parse(message.value.toString());

                    /*
                     * Shared test topic can contain messages from
                     * other Kafka integration tests, therefore only
                     * accept the exact event generated by this test.
                     */
                    if (parsedEvent.eventId !== event.eventId) {
                        return;
                    }

                    clearTimeout(timeout);

                    resolveMessage(parsedEvent);
                }

            });

            /*
             * Kafka has now assigned the test consumer its partition.
             */
            await consumerReady;

            /*
             * Publish only after partition assignment.
             */
            await producer.send({

                topic: process.env.TEST_KAFKA_TOPIC,

                messages: [
                    {
                        key: event.aggregateId,
                        value: JSON.stringify(event)
                    }
                ]

            });

            const receivedEvent = await messageReceived;

            expect(receivedEvent).toBeDefined();
            expect(receivedEvent.eventId).toBe(event.eventId);
            expect(receivedEvent.type).toBe("BALL_RECORDED");

        }
        finally {

            await producer.disconnect();
            await consumer.disconnect();

        }

    }, 30000);

});


// SRP — Test verifies producer-to-consumer delivery only.

// Factory Pattern — createTestKafka() centralizes Kafka test client creation.

// Factory Function — createEvent() centralizes event construction.

// Encapsulation — Kafka connection/security configuration stays hidden.

// Separation of Concerns — Consumer readiness, event publishing,
// and event verification remain separate phases.

// DI — Kafka infrastructure is supplied independently to the test.

// DIP — Test behavior does not depend on low-level broker configuration.